### ISSUE TITLE
Bug in column plotter with one numerical entry

### ISSUE THREAD

**Issue by meson800** [GallowayLabMIT/rushd#10]
The following crashes with a divide-by-zero error when using `rd.plot.plot_well_metadata`:
```
metadata:
    condition:
        - Tandemc: A1-H2
        - Divergentc: A3-H4
        - Convergentc: A5-H6
    dox: # ng/mL
        - 0: A1-H6
    pma: #ng/mL
        - 0: A1-H6
 ```
probably because there is only one entry so min=max
